# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('result', models.IntegerField(null=True)),
                ('status', models.IntegerField(blank=True, choices=[('processed', 1), ('pending', 0), ('not_processed', -1)], max_length=2, null=True)),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
    ]
