# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputjobs',
            name='value1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inputjobs',
            name='value2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inputjobs',
            name='result',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
