# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20161225_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inputjobs',
            options={'ordering': ('created_on',)},
        ),
        migrations.AlterField(
            model_name='inputjobs',
            name='status',
            field=models.IntegerField(blank=True, choices=[('processed', 1), ('pending', 0), ('not_processed', -1)], null=True),
        ),
    ]
